import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "./Providers";
import "@/assets/css/globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}

// TODO: W API sprawdź czy użytkownikowi został poprawnie wysłany mail, jeśli nie - usuń utworzony rekord z bazy i wyrzuć błąd.

// TODO: Zrób globalny plik na zmienne ROUTES aby nie zmieniach lokalizacji w kazdym miejscu

// TODO: Dodaj TypeScript
